### ISSUE TITLE
json-yaml-validate usage

### ISSUE THREAD

**Issue by GrantBirki** [TheDeveloperDen/LearningResources#18]
👋 Hi there @knightzmc!

I am the original author of the [json-yaml-validate](https://github.com/GrantBirki/json-yaml-validate) Action. I noticed you were using it in an open source repo, so I went to check it out and see if it was working for you alright. I stumbled across these [lines](https://github.com/TheDeveloperDen/LearningResources/blob/837a15b333cd7f2c145c7fc2e3c86e14fad7d1b0/.github/workflows/validate.yml#L1-L4) and it looks like it isn't working quite how it ideally should be.

I also noticed that your [org's fork](https://github.com/TheDeveloperDen/json-yaml-validate) is a bit ahead of the original project. If the fixes you implemented are working well, would you be able to contribute them back to the source? It might help other folks who are in the same boat as you when working with json schemas on yaml files.

Thanks!

**Comment by knightzmc** [comment]
Hey, thanks for your message! 
Yeah, those comments are a little outdated - I went through a very long process of trial & error to figure out the best way of doing it -- but using the python script meant that the error messages reported a .json file rather than .yaml so I decided to make the fork instead. 

Sure, happy to contribute - I only didn't initially as I didn't think it'd be a very common issue, or the changes would work too well. But in my (somewhat limited) experience they've worked fine.

Again thanks for your response! Will close this issue now and create a PR but feel free to re-open if you have anything else to say :)
